Removed 'smart' quotes that were accidentally pasted in Made qconf test robust against running on machine without Grid Engine installed Added fall back to running serially where Grid Engine configured but no binaries are available

diff --git a/fsl_sub b/fsl_sub
--- a/fsl_sub
+++ b/fsl_sub
@@ -23,12 +23,15 @@ METHOD=SGE
 unset module
 if [ "x$SGE_ROOT" = "x" ] ; then
 	METHOD=NONE
-fi
-
-qconf -se `hostname` >/dev/null 2>&1
-if [ $? -eq 0 ]; then
-   METHOD=NONE
-   echo ÒWarning: job submission on a cluster node attempted, running without submissionÓ >&2
+elif [ -x `which qconf` ]; then
+	qconf -se `hostname` >/dev/null 2>&1
+	if [ $? -eq 0 ]; then
+	   METHOD=NONE
+	   echo "Warning: job submission on a cluster node attempted, running without submission" >&2
+	fi
+else
+	METHOD=NONE
+	echo "Warning: SGE_ROOT environment variable is set but Grid Engine software not found" > &2
 fi
 
 # stop submitted scripts from submitting jobs themselves
