Added parallel environment option for running OpenMP jobs

diff --git a/fsl_sub b/fsl_sub
--- a/fsl_sub
+++ b/fsl_sub
@@ -60,7 +60,6 @@ map_qname ()
     #echo "Estimated time was $1 mins: queue name is $queue"
 }
 
-
 ###########################################################################
 # Don't change the following (but keep scrolling down!)
 ###########################################################################
@@ -73,7 +72,7 @@ usage ()
 {
   cat <<EOF
 
-$command V1.0beta - wrapper for job control system such as SGE
+$command V1.1 - wrapper for job control system such as SGE
 
 Usage: $command [options] <command>
 
@@ -95,6 +94,9 @@ $command -a darwin regscript rawdata outputdir ...
   -m <mailoptions>      Change the SGE mail options, see qsub for details
   -z <output>           If <output> image or file already exists, do nothing and exit
   -F                    Use flags embedded in scripts to set SGE queuing options
+  -s <pename>,<threads> Submit a multi-threaded task - requires a PE (<pename>) to be
+                        configured for the requested queues.
+                        <threads> specifies the number of threads to run
   -v                    Verbose mode.
 
 Queues:
@@ -121,7 +123,7 @@ if [ $nargs -eq 0 ] ; then
   usage
 fi
 
-set -- `getopt T:q:a:p:M:j:t:z:N:Fvm:l: $*`
+set -- `getopt T:q:a:p:M:j:t:z:N:Fvm:l:s: $*`
 result=$?
 if [ $result != 0 ] ; then
   echo "What? Your arguments make no sense!"
@@ -131,6 +133,14 @@ if [ $nargs -eq 0 ] || [ $result != 0 ] ; then
   usage
 fi
 
+###########################################################################
+# If you have a Parallel Environment configured for OpenMP tasks then
+# the variable omp_pe should be set to the name you have defined for that
+# PE. The script will work out which queues have that PE setup on them.
+# Note, we support openmp tasks even when Grid Engine is not in use.
+###########################################################################
+
+omp_pe='openmp'
 
 ###########################################################################
 # The following sets up the default queue name, which you may want to
@@ -188,6 +198,11 @@ while [ $1 != -- ] ; do
       shift;;
     -q)
       queue=$2
+      qconf -sql | grep ^$queue 2>&1 >/dev/null
+      if [ $? -eq 1 ]; then
+	  echo "Invalid queue specified!"
+	  exit 127
+      fi
       shift;;
     -a)
       acceptable_arch=no
@@ -237,6 +252,11 @@ while [ $1 != -- ] ; do
     -v)
       verbose=1
       ;;
+    -s)
+      pe_string=$2;
+      peName=`echo $pe_string | cut -d',' -f 1`
+      peThreads=`echo $pe_string | cut -d',' -f 2`
+      shift;;
   esac
   shift  # next flag
 done
@@ -266,6 +286,16 @@ if [ "x$tasks" != "x" ] && [ "x$@" != "x" ] ; then
     exit -1
 fi
 
+if [ "x$peName" != "x" ]; then
+    # If the PE name is 'openmp' then limit the number of threads to those specified
+    
+    if [ "X$peName" = "X$omp_pe" ]; then
+        OMP_NUM_THREADS=$peThreads
+	export OMP_NUM_THREADS
+    fi
+
+fi
+
 case $METHOD in
 
 ###########################################################################
@@ -276,9 +306,45 @@ case $METHOD in
 ###########################################################################
 
     SGE)
+       ###########################################################################
+       # Test Parallel environment options
+       ###########################################################################
+	if [ "x$peName" != x ]; then
+            # Is this a configured PE?
+
+	    qconf -spl | grep ^$peName 2>&1 >/dev/null
+
+	    if [ $? -eq 1 ]; then
+		echo $@
+		echo "$peName is not a valid PE"
+		exit -1
+	    fi
+
+            # Get a list of queues configured for this PE and confirm that the queue
+            # we have submitted to has that PE set up.
+	    qstat -g c -pe $peName 2>&1 >/dev/null
+	    if [ $? -eq 1 ]; then
+		echo "No parallel environments configured!"
+		exit -1
+	    fi
+
+	    qstat -g c -pe $peName | sed '1,2d' | awk '{ print $1 }' | grep ^$queue 2>&1 >/dev/null
+
+	    if [ $? -eq 1 ]; then
+		echo $@
+		echo "PE $peName is not configured on $queue"
+		exit -1
+	    fi
+
+	    # The -w e option will result in the job failing if there are insufficient slots
+            # on any of the cluster nodes
+	    pe_options="-pe $peName $peThreads -w e"
+
+	fi
+
 	if [ "x$tasks" = "x" ] ; then
 	    if [ $scriptmode -ne 1 ] ; then
-		sge_command="qsub -V -cwd -shell n -b y -r y -q $queue -M $mailto -N $JobName -m $MailOpts $LogOpts $sge_arch $sge_hold"
+		sge_command="qsub -V -cwd -shell n -b y -r y -q $queue $pe_options -M $mailto -N $JobName -m $MailOpts $LogOpts $sge_arch $sge_hold"
 	    else
 		sge_command="qsub $LogOpts $sge_arch $sge_hold"
 	    fi
@@ -288,7 +354,7 @@ case $METHOD in
 	    fi
 	    exec $sge_command $@ | awk '{print $3}'
 	else
-	    sge_command="qsub -V -cwd -q $queue -M $mailto -N $JobName -m $MailOpts $LogOpts $sge_arch $sge_hold $sge_tasks"
+	    sge_command="qsub -V -cwd -q $queue $pe_options -M $mailto -N $JobName -m $MailOpts $LogOpts $sge_arch $sge_hold $sge_tasks"
 	    if [ $verbose -eq 1 ] ; then 
 		echo sge_command: $sge_command >&2
 		echo control file: $taskfile >&2
